### PR TITLE
Do not write empty lines

### PR DESCRIPTION
**Pull request by dehru**
This PR removes those annoying empty lines that get written into your html src file.  
Example:

BEFORE
```
<!-- injector:cssvendor -->
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.css">
   ...empty line here...
   ...empty line here...
   ...empty line here...
<!-- endinjector -->
```

AFTER
```
<!-- injector:cssvendor -->
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.css">
<!-- endinjector -->
```

### CODE REVIEW

**Comment by ptitgraig** [comment]
Thanks for the PR, i'd happily merge it if you provide a unit test :)

**Comment by ptitgraig** [comment]
@dehru thanks for the PR ! Please update the readme to tell user empty files won't be included. :)

**Comment by dehru** [comment]
OK.  Memory is coming back to me on this ;-).  What this PR does is fix empty spaces that appear in the links section of the header in my index.html file.  What appears to be happening is wiredep is giving grunt injector a list of bower dependencies.  Usually not all of the dependencies have both css AND javascript.  And it's usually that there are fewer css files.  So what injector was doing was leaving an empty space in the index.html file where a dependency did not have an associated css file.  

So you get like 10 lines of javascript injected, and you also get 10 lines of css injected, but 8 of those lines would just be empty lines.  So without this fix my header would look like this:

    
    <link rel="stylesheet" href="bower_components/emc-ui/release/styles/emc-ui-bootstrap.min.css">
    <link rel="stylesheet" href="bower_components/angular-loading-bar/build/loading-bar.css">
    
    
    
    
    
    
    
    
    

But with this fix my links section looks nice and neat.

    
    <link rel="stylesheet" href="bower_components/emc-ui/release/styles/emc-ui-bootstrap.min.css">
    <link rel="stylesheet" href="bower_components/angular-loading-bar/build/loading-bar.css">
    

So I don't think there's a need for a readme comment on this, it's just improving the output that gets injected into index.html.  And helping my OCD related to empty spaces that injector was leaving in my perfectly crafted html ;-)

**Comment by dehru** [comment]
Woot!  I figured out the testing mechanism and added a test to verify that bower dependencies that do not have css files do not leave empty lines in the html file.  And all other tests are still passing...so I didn't break anything.  BTW, we've been using this fork for a lot of development and haven't seen an issue either.

**Comment by ptitgraig** [comment]
Great :) Thanks for your feedback and unit test.

**Pull request merged**
