### PR TITLE
Feature/clean

### PR DESCRIPTION
**Pull request by andreasonny83**
Introducing a `clean` option to force remove all the files listed in the template file, if any

### CODE REVIEW

**Comment by ptitgraig** [comment]
Hello, thanks for this PR. What would be the use case for such an option ?

**Comment by andreasonny83** [comment]
I'm using that option to turn on and off a mock service to inject inside my Web application while running on development mode. When I 'grunt build', instead, I want to have my app working against a real API so, using clean, I can easily avoid injecting that service inside my index.html file and I can avoid having 2 different index.html files: one for development and the other for prodction

**Comment by andreasonny83** [comment]
Wow, that's cool. I opened this PR more than 2 years ago.
I fixed the conflicts by the way so feel free to merge that in if you want.
Thanks.

**Comment by ptitgraig** [comment]
I can publish to npm and will do shortly.

**Pull request merged**
